theme: jekyll-theme-cayman
title: instrucciones
show_downloads: false
github:
  is_project_page: false
include: [".gitbook"]

# Personalización de colores (Sustituye los códigos HEX por los que desees)
header_text_color: "#FFFFFF"
header_bg_color: "#8A2920"          # Color de fondo sólido o inicio del fade
header_bg_color_secondary: "#C2961B" # Color final del fade
